@echo off
IF EXIST "C:\WINDOWS\SYSWOW64\CONFIG\SYSTEMPROFILE\APPDATA\LOCAL\SANTEDB\DCG-DEFAULT\BACKUP" (
	echo Copying backups from C:\WINDOWS\SYSWOW64\CONFIG\SYSTEMPROFILE\APPDATA\LOCAL\SANTEDB\DCG-DEFAULT\BACKUP
	IF NOT EXIST "%USERPROFILE%\Desktop\Backups" (
		echo Creating %USERPROFILE%\Desktop\Backups
		MKDIR "%USERPROFILE%\Desktop\Backups"
	)

	echo Copy Files
	COPY /Y C:\WINDOWS\SYSWOW64\CONFIG\SYSTEMPROFILE\APPDATA\LOCAL\SANTEDB\DCG-DEFAULT\BACKUP\*.SDBK %USERPROFILE%\Desktop\Backups
	EXPLORER %USERPROFILE%\Desktop\Backups
)

